ifeq ($(OS),Windows_NT)
	QT_LIB_DIR 						= C:/Qt/5.4/mingw491_32/lib
	QT_INCL_DIR 					= C:/Qt/5.4/mingw491_32/include
	QT_BIN_DIR 						= C:/Qt/5.4/mingw491_32/bin
	
	BOOST_LIB_DIR 					= Deps/lib/boost_1_58_0/Windows
	BOOST_INCL_DIR 					= Deps/incl/boost_1_58_0/Windows
else
	QT_LIB_DIR 						= /usr/lib/x86_64-linux-gnu/lib
	QT_INCL_DIR 					= /usr/lib/x86_64-linux-gnu/include
	QT_BIN_DIR 						= /usr/lib/x86_64-linux-gnu/bin
endif
