ifeq ($(OS),Windows_NT)
	QT_LIB_DIR 						= C:\Qt\Qt5.4.2\5.4\mingw491_32/lib
	QT_INCL_DIR 					= C:\Qt\Qt5.4.2\5.4\mingw491_32/include
	QT_BIN_DIR 						= C:\Qt\Qt5.4.2\5.4\mingw491_32/bin
else
	#Not needed on linux based systems
endif
