ifeq ($(OS),Windows_NT)
	QT_LIB_DIR 						= C:/Qt/5.4/mingw491_32/lib
	QT_INCL_DIR 					= C:/Qt/5.4/mingw491_32/include
	QT_BIN_DIR 						= C:/Qt/5.4/mingw491_32/bin
	
	BOOST_LIB_DIR 				= 
	BOOST_INCL_DIR 			= 
	CXXFLAGS 							+= -DWIN32
else
	#Not needed on linux based systems
endif