MODULES		+= $(QUADCOPTER_MODULE) 
MODULES		+= $(MAVLINK_EXCHANGER_MODULE)
MODULES		+= $(MAVLINK_LIB)
MODULES		+= $(SERIAL_PORT_MODULE)
MODULES		+= $(QUADCOPTER_GUI_MODULE)


SRC 		+= Src/Tests/ExampleGUITest/Main.cpp