#############################################################################
# 
# dummy Makefile for bmptk library directories
#
# (c) Wouter van Ooijen (www.voti.nl) 2012, 2013
#
# This file is in the public domain.
# 
#############################################################################

.PHONY: clean build run error

clean: error
build: error
run: error

MSG  = You are trying to build in a library directory.
MSG += You must make one of the project source files your current editor file.

error:
	$(error $(MSG) )
		
		