output: main.o
	g++ -std=c++11 -o output  -I ../../../ main.o ../../../communication/persistant_storage/databaseconnector.o -L ../../../../deps/lib/mysqlcppconn/linux/x64\(64\ bit\)/ -lmysqlcppconn -I ../../../../deps/incl/mysqlcppconn/
main.o: main.cpp
	g++ -c -std=c++11 -o main.o main.cpp -I ../../../

