output: main.o
	g++ -std=c++11 -o output main.o ../../../communication/persistant_storage/databaseconnector.o -L ../../../../deps/lib/mysqlcppconn/linux/x64\(64\ bit\)/ -lmysqlcppconn
	g++ -std=c++11 -c main.cpp -I ../../../ -I ../../../../deps/incl/mysqlcppconn/

