######################################################################
# Automatically generated by qmake (3.0) Sat Feb 21 14:46:53 2015
######################################################################

TEMPLATE = app
TARGET = Daniel_van_den_Berg
INCLUDEPATH += .

# Input
HEADERS += MapSystem/mapeditor.h
FORMS += MapSystem/mainwindow.ui
SOURCES += test.cpp \
    MapSystem/mapeditor.cpp
