#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
#############################################################################

# Specify the project name (default is main)
# this is also the main .c, .cpp or .asm file to compile
PROJECT    := 

# Specify target chip or board or system
TARGET     := lpc1114fn28

# Specify the location of the bmptk library
BMPTK      := ../../..

# Specify project files (other than $(PROJECT).cpp) (if any)
OBJECTS    := 
SOURCES    := timer.c
HEADERS    := timer.h
LIBRARIES  :=
SEARCH     :=

# specify (extra) results you want to get (if any)
RESULTS    := 

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
