#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
#############################################################################

# Specify the project name, this is also the main .cpp file to compile
PROJECT    := 

# Specify target chip or board or system
TARGET     := lpc1114fn28

# Specify the location of the bmptk library
BMPTK      := ../..

# Specify project files (other than $(PROJECT).*) (if any)
OBJECTS    := 
SOURCES    :=
HEADERS    :=
LIBRARIES  := sw-uart timer adc_direct ports
SEARCH     := ../../library

# specify (extra) results you want to get (if any)
RESULTS    := 

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc