CXX 		+= 
CXXFLAGS	+= 
INCLUDES 	+= -I$(BOOST_INCL_DIR)
LDLIBS		+= -lboost_system -lws2_32
LDFLAGS		+= -L$(BOOST_LIB_DIR)
MODULES		+= $(QUADCOPTER_MODULE) 
MODULES		+= $(MAVLINK_EXCHANGER_MODULE)
MODULES		+= $(MAVLINK_LIB)
MODULES		+= $(SERIAL_PORT_MODULE)
MODULES		+= $(QUADCOPTER_CONTROLLER_MODULE)
MODULES		+= $(LOCALISATION_BASESTATION)


SRC 		+= Src/Tests/QuadcopterControllerTest/Main.cpp