CXX 		+= 
CXXFLAGS	+= 
INCLUDES 	+= 
LDLIBS		+= 
LDFLAGS		+= 
MODULES		+= $(QUADCOPTER_MODULE) 
MODULES		+= $(MAVLINK_EXCHANGER_MODULE)
MODULES		+= $(MAVLINK_LIB)
MODULES		+= $(SERIAL_PORT_MODULE)
MODULES		+= $(QUADCOPTER_CONTROLLER_MODULE)
MODULES		+= $(LOCALISATION_BASESTATION)


SRC 		+= Src/Tests/QuadcopterControllerTest/Main.cpp