CXX 		+= 
CXXFLAGS	+= 
INCLUDES 	+= 
LDFLAGS		+= 
LDLIBS 		+= 
MODULES 	+= $(STRATEGY_PAIRWISE_MODULE)
MODULES		+= $(STRATEGY_COMMON_MODULE)
MODULES 	+= $(STRATEGY_TINYASTAR_MODULE)
MODULES 	+= $(ATV_MODULE)
MODULES 	+= $(ROSBEE_LOCAL_MODULE)
MODULES 	+= $(UDP_MODULE)
MODULES 	+= $(MAVLINK_LIB)
MODULES		+= $(LIDAR_BASESTATION_MODULE)
MODULES		+= $(MAVLINK_EXCHANGER_MODULE)
MODULES		+= $(UDP_RASPI)
MODULES 	+= $(SERIAL_PORT_MODULE)
MODULES 	+= $(MAP_COMMON_MODULE)
MODULES 	+= $(MAP_STRUCTURE_MODULE)


SRC			+= Src/Tests/PairWiseTest/Main.cpp