#ifndef SIMULATEMAP_H
#define SIMULATEMAP_H
#include "map.h"
#include "../point_clouds/pointcloud object/PointCloud.h"
#include "checkpoint.h"

//! The Simulate class
/*!
The object which will contain all simulation data
*/
class SimulateMap
{
private:
    int lidarX = 0; //Coordinates of the lidar
    int lidarY = 0; //coordinates of the lidar
    std::vector<checkPoint> checkpoints;
    Map *map; //Pointer to the map
    Pointcloud pC;
public:
    //! The simulateMap constructor for an existing map
    /*!
    Create a simulateMap object from an existing map
    @param map: the vector containing the map
    */
    SimulateMap(Map *map);
    //! Perform a simulation on the given map
    /*!
    Detect all objects around the lidar and return a pointcloud containt the coordinates
    @return String containing the found objects for the GUI to display
    */
    std::string simulate();
    //! Set the scanpoint(the point where the lidar is located)
    /*!
    Set the scanpoint of the Lidar
    */
    void setScanPoint(int y, int x);
    //! Add checkpoints to the checkpoint vector
    /*!
    Add new checkpoints to the vector for simulation
    @param x: the x coordinates of the given checkpoint
    @param y: the y coordinates of the given checkpoint
    */
    void addCheckPoint(int x, int y);
    //! Returns the pointcloud produced by the simulation
    /*!
    Returns the pointcloud generated by the simulation
    @return Pointcloud containing the detected objects
    */
    Pointcloud getPointCloud();
    //! Default destructor of simulate map
    /*!
      The default destructor of simulate map
    */
    ~SimulateMap();
};

#endif // SIMULATEMAP_H
